[tool.poetry]
name = "data-analysis"
version = "0.1.0"
description = "Data analysis notebooks with python"
authors = ["Jose R. Zapata "]
readme = "README.md"
packages = [{include = "data_analysis"}]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
pandas = "^2.1.1"
plotly = "^5.18.0"
numpy = "^1.24.3"
chart-studio = "^1.1.0"
seaborn = "^0.13.0"
pyarrow = "^14.0.1"
ipywidgets = "^8.1.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
