[tool.poetry]
name = "Data analysis notebooks with python"
version = "0.1.0"
description = "Data analysis notebooks with python"
authors = ["Jose R. Zapata"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
hydra-core = "^1.1.1"
#
# Jupyter Notebook
jupyter = "^1.0.0"
#


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"

# Standardized Developer Workflow Orchestration
cruft = "^2.15.0" # Automated Cookiecutter template synchronization


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
coverage = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.virtualenvs]
in-project = true
