[tool.poetry]
name = "covid-plots"
version = "0.1.0"
description = "plotly graphs of covid data"
authors = ["Jose R. Zapata <jjrzg@hotmail.com>"]
readme = "README.md"
packages = [{include = "covid_plots"}]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
pandas = "^2.1.1"
plotly = "^5.17.0"
numpy = "^1.24.3"
chart-studio = "^1.1.0"
seaborn = "^0.13.0"
pyarrow = "^14.0.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
